# Generated by Django 4.2.7 on 2023-12-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teto', '0002_post_create_time_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('thoughts', '感想'), ('advertisement', '宣伝')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
