# Generated by Django 4.2.7 on 2023-12-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teto', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('感想', '感想'), ('宣伝', '宣伝')], max_length=100),
        ),
    ]
