# Generated by Django 4.2.7 on 2024-01-29 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teto', '0007_alter_post_options_alter_post_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
